name: GitHub My Coverity Workflow
# Use this YAML in your workflow file for each job

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-on-self-hosted:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show current working directory
        run: |
          pwd

