name: GitHub My Coverity Workflow
# Use this YAML in your workflow file for each job
# Example: https://documentation.blackduck.com/ja-JP/bundle/bridge/page/documentation/c_github-coverity.html


on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-on-self-hosted:
    # runs-on: [ ubuntu-latest ]
    runs-on: self-hosted
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show current working directory
        run: |
          pwd

      - name: Build the app
        run: |
          g++ test.cpp

      - name: Run the app
        run: |
          ./a.out

#      - name: Coverity BAC
#        run: |
#          cov-configure --gcc --config config/config.xml
#          cov-build --dir idir --config config/config.xml g++ test.cpp
#          cov-analyze --dir idir --all

